import{jsx as _jsx}from"react/jsx-runtime";import*as React from"react";import{addPropertyControls,ControlType,RenderTarget}from"framer";const DEFAULT_SELECTOR="header, nav, [data-framer-name*='Navigation' i], [data-framer-name*='Nav' i]";const PANEL_SELECTOR="[data-playground-panel='true']";const CLOSE_BUTTON_SELECTOR="button[aria-label='Close detail']";const BODY_CLASS="playground-sidebar-nav-exit-hold";const STYLE_ID="playground-sidebar-nav-exit-hold-style";function scopedSelectors(selector){return selector.split(",").map(part=>part.trim()).filter(Boolean).map(part=>`body.${BODY_CLASS} ${part}`);}function getPanel(){return document.querySelector(PANEL_SELECTOR);}function isPanelOpen(panel){return Boolean(panel&&window.getComputedStyle(panel).pointerEvents!=="none");}function getElementTarget(event){return event.target instanceof Element?event.target:null;}/**
 * Playground Nav Exit Hold
 *
 * Keeps the site nav hidden until the playground sidebar has finished sliding out.
 *
 * @framerIntrinsicWidth 1
 * @framerIntrinsicHeight 1
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight fixed
 */export default function PlaygroundNavExitHold(props){const{enabled=true,selector=DEFAULT_SELECTOR,durationMs=950,style}=props;const target=RenderTarget.current();const isCanvas=target===RenderTarget.canvas||target===RenderTarget.thumbnail;React.useEffect(()=>{if(!enabled||isCanvas||typeof window==="undefined"||typeof document==="undefined")return;const navSelectors=scopedSelectors(selector);if(!navSelectors.length)return;let styleEl=document.getElementById(STYLE_ID);if(!styleEl){styleEl=document.createElement("style");styleEl.id=STYLE_ID;document.head.appendChild(styleEl);}styleEl.textContent=`
            ${navSelectors.join(",\n")} {
                opacity: 0 !important;
                visibility: hidden !important;
                pointer-events: none !important;
            }
        `;let releaseTimer=0;let wasOpen=isPanelOpen(getPanel());const releaseHold=()=>{document.body.classList.remove(BODY_CLASS);};const holdNav=()=>{window.clearTimeout(releaseTimer);document.body.classList.add(BODY_CLASS);releaseTimer=window.setTimeout(releaseHold,Math.max(0,durationMs));};const onPointerDown=event=>{const panel=getPanel();if(!isPanelOpen(panel))return;const targetElement=getElementTarget(event);const closeButton=targetElement?.closest(CLOSE_BUTTON_SELECTOR);const insidePanel=targetElement?.closest(PANEL_SELECTOR);if(closeButton||!insidePanel)holdNav();};const onKeyDown=event=>{if(event.key==="Escape"&&isPanelOpen(getPanel()))holdNav();};const pollPanelState=()=>{const open=isPanelOpen(getPanel());if(wasOpen&&!open)holdNav();wasOpen=open;};document.addEventListener("pointerdown",onPointerDown,true);window.addEventListener("keydown",onKeyDown,true);const interval=window.setInterval(pollPanelState,50);return()=>{document.removeEventListener("pointerdown",onPointerDown,true);window.removeEventListener("keydown",onKeyDown,true);window.clearInterval(interval);window.clearTimeout(releaseTimer);releaseHold();if(styleEl?.parentNode)styleEl.parentNode.removeChild(styleEl);};},[enabled,selector,durationMs,isCanvas]);return /*#__PURE__*/_jsx("div",{"aria-hidden":"true",style:{...style,width:"100%",height:"100%",opacity:0,pointerEvents:"none"}});}addPropertyControls(PlaygroundNavExitHold,{enabled:{type:ControlType.Boolean,title:"Enabled",defaultValue:true,enabledTitle:"On",disabledTitle:"Off"},selector:{type:ControlType.String,title:"Nav Selector",defaultValue:DEFAULT_SELECTOR},durationMs:{type:ControlType.Number,title:"Hold Time",defaultValue:950,min:300,max:1600,step:50,unit:"ms"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"PlaygroundNavExitHold","slots":[],"annotations":{"framerSupportedLayoutHeight":"fixed","framerIntrinsicHeight":"1","framerSupportedLayoutWidth":"fixed","framerContractVersion":"1","framerIntrinsicWidth":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./PlaygroundNavExitHold.map