// Get Started: https://www.framer.com/developers
import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{addPropertyControls,ControlType,RenderTarget}from"framer";import{useEffect,useMemo}from"react";function getRegistry(){if(typeof window==="undefined")return null;const w=window;if(!w.__articaIndexProjectsRegistry){const items=new Map;const listeners=new Set;const registry={items,listeners,register(id,data){items.set(id,data);listeners.forEach(fn=>fn(items));},unregister(id){items.delete(id);listeners.forEach(fn=>fn(items));},subscribe(fn){listeners.add(fn);fn(items);return()=>{listeners.delete(fn);};}};w.__articaIndexProjectsRegistry=registry;}return w.__articaIndexProjectsRegistry??null;}function normalizeAssetSrc(value){if(!value)return undefined;if(typeof value==="string")return value;if(Array.isArray(value)){return value.map(normalizeAssetSrc).find(Boolean);}return normalizeAssetSrc(value.src)||normalizeAssetSrc(value.url)||normalizeAssetSrc(value.href)||normalizeAssetSrc(value.file)||normalizeAssetSrc(value.value);}// Build a deterministic registry id from the row's content. Using slug (or
// title as fallback) means responsive breakpoints (Desktop/Tablet/Phone) and
// React StrictMode double-mounts collapse into a single entry instead of
// producing duplicates. Falls back to a random id if neither slug nor title
// is available, so empty/draft rows still register without colliding.
function buildRegistryId(props){if(props.slug&&typeof props.slug==="string"&&props.slug.trim()){return`slug:${props.slug.trim()}`;}if(props.title&&typeof props.title==="string"&&props.title.trim()){return`title:${props.title.trim().toLowerCase()}`;}return`pr_${Math.random().toString(36).slice(2)}_${Date.now()}`;}/**
 * @framerSupportedLayoutWidth auto
 * @framerSupportedLayoutHeight auto
 */export default function ProjectRegistrar(props){const id=useMemo(()=>buildRegistryId(props),[props.slug,props.title]);const projectData=useMemo(()=>{const thumb=normalizeAssetSrc(props.thumbnail);const thumbnailVideo=normalizeAssetSrc(props.thumbnailVideoLink);return{title:props.title||"",category1:props.category1||"",category2:props.category2||"",category3:props.category3||"",industry:props.industry||"",year:props.year||"",thumbnail:thumb||undefined,thumbnailVideoLink:thumbnailVideo||"",thumbnailStroke:!!props.thumbnailStroke,slug:props.slug||"",sortOrder:typeof props.sortOrder==="number"?props.sortOrder:undefined,isHomepage:!!props.isHomepage};},[props.title,props.category1,props.category2,props.category3,props.industry,props.year,props.thumbnail,props.thumbnailVideoLink,props.thumbnailStroke,props.slug,props.sortOrder,props.isHomepage]);useEffect(()=>{const reg=getRegistry();if(!reg)return;reg.register(id,projectData);return()=>{reg.unregister(id);};},[id,projectData]);// Show a small labelled badge on the Framer canvas so the component is
// visible (and selectable) during editing, but render absolutely nothing
// on the published site so the design isn't affected.
const isCanvas=RenderTarget.current()===RenderTarget.canvas;if(!isCanvas){return null;}const labelText=props.title?String(props.title):"ProjectRegistrar";return /*#__PURE__*/_jsxs("div",{"aria-hidden":"true",style:{display:"inline-flex",alignItems:"center",gap:6,padding:"4px 8px",width:"fit-content",maxWidth:240,height:22,fontFamily:"'GT Standard Mono', 'GT Standard Mono Trial', 'SF Mono', 'Menlo', monospace",fontSize:10,lineHeight:1,color:"rgba(20, 20, 20, 0.7)",background:"rgba(20, 20, 20, 0.06)",border:"1px dashed rgba(20, 20, 20, 0.35)",borderRadius:3,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis",pointerEvents:"none",userSelect:"none"},children:[/*#__PURE__*/_jsx("span",{style:{opacity:.6},children:"."}),/*#__PURE__*/_jsx("span",{style:{overflow:"hidden",textOverflow:"ellipsis"},children:labelText})]});}addPropertyControls(ProjectRegistrar,{title:{type:ControlType.String,title:"Title"},category1:{type:ControlType.String,title:"Category 1"},category2:{type:ControlType.String,title:"Category 2"},category3:{type:ControlType.String,title:"Category 3"},industry:{type:ControlType.String,title:"Industry"},year:{type:ControlType.String,title:"Year"},thumbnail:{type:ControlType.Image,title:"Thumbnail"},thumbnailVideoLink:{type:ControlType.File,title:"Thumbnail Video",allowedFileTypes:["mp4","webm","mov"]},thumbnailStroke:{type:ControlType.Boolean,title:"Thumbnail Stroke"},slug:{type:ControlType.String,title:"Slug"},sortOrder:{type:ControlType.Number,title:"Sorting Number"},isHomepage:{type:ControlType.Boolean,title:"Is Homepage"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"ProjectRegistrar","slots":[],"annotations":{"framerSupportedLayoutHeight":"auto","framerContractVersion":"1","framerSupportedLayoutWidth":"auto"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Test.map