import{jsx as _jsx}from"react/jsx-runtime";import*as React from"react";import{addPropertyControls,ControlType}from"framer";const processImages=[{src:"https://framerusercontent.com/images/lwDyNtPzXOD9AduncyTRjp3fyQ.jpg",alt:"TYPLDN process photo showing printed material on a table",ratio:4/3},{src:"https://framerusercontent.com/images/59Hl2ZuNkNHnxRZTlyi8OTUiE.jpg",alt:"TYPLDN process photo showing conference material exploration",ratio:4/3},{src:"https://framerusercontent.com/images/S48fzkrSDGrXw1LZTDpdgQyCNQ.jpg",alt:"TYPLDN process photo showing printed identity details",ratio:4/3},{src:"https://framerusercontent.com/images/i1t6WtlWWhSe6HEt2ucu9UReuY.jpg",alt:"TYPLDN process photo showing vertical signage or printed output",ratio:3/4},{src:"https://framerusercontent.com/images/PMeNWxKbmPLIPPoRpHdWk22zI.jpg",alt:"TYPLDN process photo showing a portrait-format process image",ratio:3/4}];const ratioTotal=processImages.reduce((sum,image)=>sum+image.ratio,0);const gapCount=processImages.length-1;function justifiedWidth(ratio,totalGap,availableWidth,containerWidth){if(containerWidth>0)return availableWidth*ratio/ratioTotal;const percentage=ratio/ratioTotal*100;const gapShare=totalGap*ratio/ratioTotal;return`calc(${percentage}% - ${gapShare}px)`;}/**
 * TYPLDN Process Gallery
 *
 * A Cargo-style process image strip for the TYPLDN case study. Images keep their
 * original aspect ratios and the strip always fills the full container width.
 *
 * @framerIntrinsicWidth 1120
 * @framerIntrinsicHeight 180
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight auto
 */export default function TypldnProcessGallery(props){const{rowHeight=180,minRowHeight=44,gap=20,mobileGap=5,style}=props;const rootRef=React.useRef(null);const[containerWidth,setContainerWidth]=React.useState(0);React.useLayoutEffect(()=>{const root=rootRef.current;if(!root||typeof ResizeObserver==="undefined")return;const updateWidth=()=>setContainerWidth(root.clientWidth);updateWidth();const resizeObserver=new ResizeObserver(updateWidth);resizeObserver.observe(root);return()=>resizeObserver.disconnect();},[]);const safeRowHeight=Math.max(1,Number(rowHeight)||180);const safeMinRowHeight=Math.max(1,Number(minRowHeight)||44);const wideGap=Math.max(0,Number(gap)||0);const narrowGap=Math.max(0,Number(mobileGap)||0);const naturalWidth=ratioTotal*safeRowHeight+gapCount*wideGap;const shouldUseNarrowGap=containerWidth>0&&containerWidth<naturalWidth;const effectiveGap=shouldUseNarrowGap?narrowGap:wideGap;const totalGap=gapCount*effectiveGap;const availableWidth=Math.max(1,containerWidth-totalGap);const fittedHeight=containerWidth>0?availableWidth/ratioTotal:safeRowHeight;const effectiveRowHeight=Math.max(safeMinRowHeight,fittedHeight);return /*#__PURE__*/_jsx("div",{ref:rootRef,style:{...style,width:"100%",height:effectiveRowHeight,overflow:"hidden",background:"transparent"},"aria-label":"TYPLDN process gallery",children:/*#__PURE__*/_jsx("div",{style:{display:"flex",alignItems:"flex-start",gap:effectiveGap,width:"100%",height:effectiveRowHeight,background:"transparent"},children:processImages.map(image=>/*#__PURE__*/_jsx("img",{src:image.src,alt:image.alt,draggable:false,style:{display:"block",width:justifiedWidth(image.ratio,totalGap,availableWidth,containerWidth),height:effectiveRowHeight,objectFit:"contain",objectPosition:"center",borderRadius:0,flex:"0 0 auto",boxSizing:"border-box",background:"transparent"}},image.src))})});}addPropertyControls(TypldnProcessGallery,{rowHeight:{type:ControlType.Number,title:"Target H",defaultValue:180,min:80,max:360,step:1,unit:"px"},minRowHeight:{type:ControlType.Number,title:"Min Height",defaultValue:44,min:24,max:120,step:1,unit:"px"},gap:{type:ControlType.Number,title:"Gap",defaultValue:20,min:0,max:80,step:1,unit:"px"},mobileGap:{type:ControlType.Number,title:"Mobile Gap",defaultValue:5,min:0,max:24,step:1,unit:"px"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"TypldnProcessGallery","slots":[],"annotations":{"framerSupportedLayoutWidth":"any","framerIntrinsicHeight":"180","framerContractVersion":"1","framerIntrinsicWidth":"1120","framerSupportedLayoutHeight":"auto"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./TypldnProcessGallery.map