import{jsx as _jsx}from"react/jsx-runtime";import*as React from"react";import{addPropertyControls,ControlType,RenderTarget}from"framer";const PANEL_SELECTOR="[data-playground-panel='true']";const RULE_SELECTOR="[data-playground-detail-rule='true'], .playground-detail-rule";function getDetailGrid(panel){const figure=panel?.querySelector("figure");if(!figure)return null;let next=figure.nextElementSibling;while(next&&next.matches(RULE_SELECTOR))next=next.nextElementSibling;return next;}function applyColumnGuard(columnGap,breakpoint){const panel=document.querySelector(PANEL_SELECTOR);const detailGrid=getDetailGrid(panel);if(!panel||!detailGrid)return;const panelWidth=panel.getBoundingClientRect().width;const shouldStack=panelWidth>0&&panelWidth<breakpoint;const titleColumn=detailGrid.children[0];const description=detailGrid.children[1];const title=titleColumn?.querySelector("h2");Object.assign(detailGrid.style,{display:"grid",gridTemplateColumns:shouldStack?"minmax(0, 1fr)":"minmax(0, 1.08fr) minmax(0, .92fr)",gap:shouldStack?"18px":`${Math.max(0,columnGap)}px`,alignItems:"start",width:"100%",maxWidth:"100%",minWidth:"0"});if(titleColumn){Object.assign(titleColumn.style,{minWidth:"0",maxWidth:"100%",overflow:"hidden"});}if(title){Object.assign(title.style,{maxWidth:"100%",minWidth:"0",lineHeight:"1.06",overflowWrap:"anywhere",wordBreak:"normal",hyphens:"auto"});}if(description){Object.assign(description.style,{minWidth:"0",maxWidth:"100%",overflowWrap:"break-word",wordBreak:"normal"});}}/**
 * Playground Sidebar Column Guard
 *
 * Keeps the playground sidebar title and description in separate, non-overlapping columns.
 *
 * @framerIntrinsicWidth 1
 * @framerIntrinsicHeight 1
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight fixed
 */export default function PlaygroundSidebarColumnGuard(props){const{enabled=true,columnGap=28,breakpoint=430,style}=props;const target=RenderTarget.current();const isCanvas=target===RenderTarget.canvas||target===RenderTarget.thumbnail;React.useEffect(()=>{if(!enabled||isCanvas||typeof window==="undefined"||typeof document==="undefined")return;let raf=0;const syncNow=()=>{raf=0;applyColumnGuard(columnGap,breakpoint);};const sync=()=>{if(raf)return;raf=window.requestAnimationFrame(syncNow);};sync();const observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true,characterData:true});window.addEventListener("resize",sync);document.addEventListener("load",sync,true);document.addEventListener("loadedmetadata",sync,true);return()=>{if(raf)window.cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener("resize",sync);document.removeEventListener("load",sync,true);document.removeEventListener("loadedmetadata",sync,true);};},[enabled,columnGap,breakpoint,isCanvas]);return /*#__PURE__*/_jsx("div",{"aria-hidden":"true",style:{...style,width:"100%",height:"100%",opacity:0,pointerEvents:"none"}});}addPropertyControls(PlaygroundSidebarColumnGuard,{enabled:{type:ControlType.Boolean,title:"Enabled",defaultValue:true,enabledTitle:"On",disabledTitle:"Off"},columnGap:{type:ControlType.Number,title:"Column Gap",defaultValue:28,min:12,max:56,step:2,unit:"px"},breakpoint:{type:ControlType.Number,title:"Stack Below",defaultValue:430,min:320,max:560,step:10,unit:"px"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"PlaygroundSidebarColumnGuard","slots":[],"annotations":{"framerContractVersion":"1","framerSupportedLayoutHeight":"fixed","framerIntrinsicWidth":"1","framerSupportedLayoutWidth":"fixed","framerIntrinsicHeight":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./PlaygroundSidebarColumnGuard.map