import{jsx as _jsx}from"react/jsx-runtime";import{addPropertyControls,ControlType}from"framer";function getYouTubeId(src){if(!src)return"";try{const url=new URL(src);const host=url.hostname.replace(/^www\./,"");if(host==="youtu.be"){return url.pathname.split("/").filter(Boolean)[0]||"";}if(host==="youtube.com"||host==="m.youtube.com"){if(url.pathname==="/watch")return url.searchParams.get("v")||"";const parts=url.pathname.split("/").filter(Boolean);if(["embed","shorts","live"].includes(parts[0]))return parts[1]||"";}}catch{const match=src.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/|live\/))([^?&#/]+)/);return match?.[1]||"";}return"";}function buildYouTubeEmbedUrl(src,props){const videoId=getYouTubeId(src);if(!videoId)return"";const params=new URLSearchParams({autoplay:props.autoplay?"1":"0",controls:props.controls?"1":"0",loop:props.loop?"1":"0",playsinline:"1",rel:"0"});if(props.loop)params.set("playlist",videoId);if(props.muted)params.set("mute","1");return`https://www.youtube.com/embed/${videoId}?${params.toString()}`;}/**
 * Responsive Case Study Video
 *
 * @framerIntrinsicWidth 1600
 * @framerIntrinsicHeight 900
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight any
 */export default function ResponsiveCaseStudyVideo(props){const{src,poster,ratio,autoplay,loop,muted,controls,title,style}=props;const isImageSource=/\.(gif|jpe?g|png|webp|avif|svg)(\?.*)?$/i.test(src);const youtubeEmbedUrl=buildYouTubeEmbedUrl(src,props);return /*#__PURE__*/_jsx("div",{style:{...style,width:"100%",height:"auto",aspectRatio:ratio,display:"block",overflow:"hidden",background:"transparent"},children:isImageSource?/*#__PURE__*/_jsx("img",{src:src,alt:title||"Case study media",loading:"lazy",style:{display:"block",width:"100%",height:"100%",objectFit:"contain",background:"transparent"}}):youtubeEmbedUrl?/*#__PURE__*/_jsx("iframe",{src:youtubeEmbedUrl,title:title||"YouTube video",allow:"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share",allowFullScreen:true,style:{display:"block",width:"100%",height:"100%",border:0,background:"transparent"}}):/*#__PURE__*/_jsx("video",{src:src,poster:poster||undefined,autoPlay:autoplay,loop:loop,muted:muted,controls:controls,playsInline:true,preload:"metadata",style:{display:"block",width:"100%",height:"100%",objectFit:"contain",background:"transparent"}})});}addPropertyControls(ResponsiveCaseStudyVideo,{src:{type:ControlType.String,title:"Source",defaultValue:""},poster:{type:ControlType.String,title:"Poster",defaultValue:""},ratio:{type:ControlType.Number,title:"Ratio",defaultValue:1.7777777778,min:.2,max:4,step:.01},autoplay:{type:ControlType.Boolean,title:"Autoplay",defaultValue:true},loop:{type:ControlType.Boolean,title:"Loop",defaultValue:true},muted:{type:ControlType.Boolean,title:"Muted",defaultValue:true},controls:{type:ControlType.Boolean,title:"Controls",defaultValue:false},title:{type:ControlType.String,title:"Title",defaultValue:"Case study video"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"ResponsiveCaseStudyVideo","slots":[],"annotations":{"framerSupportedLayoutWidth":"any","framerIntrinsicWidth":"1600","framerSupportedLayoutHeight":"any","framerContractVersion":"1","framerIntrinsicHeight":"900"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./ResponsiveCaseStudyVideo.map