import{jsx as _jsx}from"react/jsx-runtime";import*as React from"react";import{addPropertyControls,ControlType,RenderTarget}from"framer";const SNAPSHOT_SELECTOR="[data-playground-exit-snapshot='true']";const RULE_ATTR="data-playground-detail-rule";const STYLE_ID="playground-rule-exit-guard-style";function styleExitRule(rule,ruleColor){rule.classList.add("playground-detail-rule");rule.setAttribute(RULE_ATTR,"true");rule.setAttribute("aria-hidden","true");Object.assign(rule.style,{width:"100%",height:"1px",background:ruleColor,margin:"clamp(28px, 4vw, 54px) 0 clamp(12px, 1.5vw, 18px)",transformOrigin:"left center",transform:"scaleX(1)",animation:"none",willChange:"auto"});}function ensureSnapshotRules(ruleColor){document.querySelectorAll(SNAPSHOT_SELECTOR).forEach(snapshot=>{snapshot.querySelectorAll("figure").forEach(figure=>{const next=figure.nextElementSibling;if(next?.getAttribute(RULE_ATTR)==="true"){styleExitRule(next,ruleColor);return;}const rule=document.createElement("div");styleExitRule(rule,ruleColor);figure.insertAdjacentElement("afterend",rule);});});}/**
 * Playground Rule Exit Guard
 *
 * Keeps the detail divider mounted in the sidebar exit snapshot so text spacing stays stable while the panel closes.
 *
 * @framerIntrinsicWidth 1
 * @framerIntrinsicHeight 1
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight fixed
 */export default function PlaygroundRuleExitGuard(props){const{enabled=true,ruleColor="#233324",style}=props;const target=RenderTarget.current();const isCanvas=target===RenderTarget.canvas||target===RenderTarget.thumbnail;React.useEffect(()=>{if(!enabled||isCanvas||typeof window==="undefined"||typeof document==="undefined")return;const originalRemove=Element.prototype.remove;const guardedRemove=function(){if(this instanceof HTMLElement&&this.getAttribute(RULE_ATTR)==="true"&&this.closest(SNAPSHOT_SELECTOR))return;return originalRemove.call(this);};Element.prototype.remove=guardedRemove;let styleEl=document.getElementById(STYLE_ID);if(!styleEl){styleEl=document.createElement("style");styleEl.id=STYLE_ID;document.head.appendChild(styleEl);}styleEl.textContent=`${SNAPSHOT_SELECTOR} .playground-detail-rule { animation: none !important; transform: scaleX(1) !important; will-change: auto !important; }`;let raf=0;const syncNow=()=>{raf=0;ensureSnapshotRules(ruleColor);};const sync=()=>{if(raf)return;raf=window.requestAnimationFrame(syncNow);};sync();const observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true});return()=>{if(raf)window.cancelAnimationFrame(raf);observer.disconnect();if(Element.prototype.remove===guardedRemove)Element.prototype.remove=originalRemove;if(styleEl?.parentNode)styleEl.parentNode.removeChild(styleEl);};},[enabled,isCanvas,ruleColor]);return /*#__PURE__*/_jsx("div",{"aria-hidden":"true",style:{...style,width:"100%",height:"100%",opacity:0,pointerEvents:"none"}});}addPropertyControls(PlaygroundRuleExitGuard,{enabled:{type:ControlType.Boolean,title:"Enabled",defaultValue:true,enabledTitle:"On",disabledTitle:"Off"},ruleColor:{type:ControlType.Color,title:"Rule",defaultValue:"#233324"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"PlaygroundRuleExitGuard","slots":[],"annotations":{"framerSupportedLayoutWidth":"fixed","framerIntrinsicWidth":"1","framerSupportedLayoutHeight":"fixed","framerContractVersion":"1","framerIntrinsicHeight":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./PlaygroundRuleExitGuard.map